### ISSUE TITLE
Syntax highlighting doesn't work

### ISSUE THREAD

**Issue by DavHau** [nix-community/vscode-nix-ide#4] opened 2020-09-25 06:22 UTC
```nix
let
  pkgs = import (builtins.fetchTarball {
    # nixos unstable
    url = "https://github.com/nixos/nixpkgs-channels/tarball/a31736120c5de6e632f5a0ba1ed34e53fc1c1b00";
    sha256 = "0xfjizw6w84w1fj47hxzw2vwgjlszzmsjb8k8cgqhb379vmkxjfl";
  }) {config = {}; overlays = [];};
  vscode-nix-ide = builtins.fetchGit {
    url = "https://github.com/nix-community/vscode-nix-ide";
    rev = "699c803e056d9ef080061c211ace0518dbcb4fc4";
  };
  codium-nix = pkgs.writeScriptBin "codium-nix" ''
    #!/usr/bin/env bash
    ${pkgs.vscodium}/bin/codium --extensions-dir ${
      pkgs.runCommand "extensions-dir" { buildInputs = [ vscode-nix-ide ]; } ''
        mkdir $out
        cp -r ${vscode-nix-ide} $out/vscode-nix-ide
      ''
    } --user-data-dir $(pwd)/.data $@
  '';
in
pkgs.mkShell {
  buildInputs = [ codium-nix ];
}
```

Inside this shell, run `codium-nix`. The extension is enabled in the settings, but doesn't seem to do anything

**Comment by jnoortheen** [comment] 2020-09-25 07:37
the extension needs to be compiled. It is in Typescript and also the syntax file need to be compiled to json. please check the `package.json` script commands

**Comment by jnoortheen** [comment] 2020-09-25 07:42
https://github.com/nix-community/vscode-nix-ide#development

```
yarn build
```
is a build step needed. Or you could directly use the vix file from vscode extension store.

**Comment by DavHau** [comment] 2020-09-25 07:51
Thanks a lot!!

Currently I'm trying to figure out how to get a permanent of the vsix extension file.
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/jnoortheen/vsextensions/nix-ide/0.1.3/vspackage
raises error 429 when downlaoded from cmdline

**Comment by jnoortheen** [comment] 2020-09-28 10:03
The issue is related to build steps rather than the code itself. I am closing it. Feel free to ask any issues encountered building with nix.

**Closed by jnoortheen** 2020-09-28 10:03 UTC
